name: Build & Publish Release APK


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      run: bash ./gradlew assembleRelease
    - name: Setup build tool version variable
      shell: bash
      run: |
        BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
        echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
        echo Last build tool version is: $BUILD_TOOL_VERSION
      
    - uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        # override default build-tools version (29.0.3) -- optional
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

    - run: mv ${{steps.sign_app.outputs.signedReleaseFile}} $GITHUB_REF_NAME.apk

    - name: Upload APK to Github
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: $GITHUB_REF_NAME.apk

    # - uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "*.apk"
    #     token: ${{ secrets.TOKEN }}
    #     generateReleaseNotes: true